# Generated by Django 4.2.2 on 2023-06-23 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('NP', 'Nepali')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profilepics'),
        ),
    ]
