# Generated by Django 4.2.2 on 2023-06-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_language_alter_author_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
