# Generated by Django 4.2.2 on 2023-06-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_vacancy_status_vacancy_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='tender_documents')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_expiry', models.DateField()),
            ],
        ),
    ]
