# Generated by Django 4.2.2 on 2023-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_author_slug_appliedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
