# Generated by Django 4.2.2 on 2023-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_post_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaper_pdf', models.FileField(upload_to='epapers')),
                ('date_created', models.DateField()),
            ],
        ),
    ]
