# Generated by Django 4.2.2 on 2023-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_post_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='breaking_thumbs')),
            ],
        ),
    ]
