# Generated by Django 4.2.2 on 2023-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_breakings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbs'),
        ),
    ]
