# Generated by Django 4.2.2 on 2023-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_post_breaking_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='breakingthumbnail',
            field=models.BooleanField(default=True),
        ),
    ]
