# Generated by Django 4.2.2 on 2023-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_category_grid_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='profilepics'),
        ),
    ]
