# Generated by Django 4.2.2 on 2023-07-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_author_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='date_expiry',
        ),
    ]
