# Generated by Django 4.2.2 on 2023-07-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_advertisement_date_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='breakings',
        ),
    ]
