# Generated by Django 4.2.2 on 2023-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_comments_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='hits',
            field=models.IntegerField(default=1),
        ),
    ]
