# Generated by Django 4.2.2 on 2023-08-21 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_advertisement_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 10, 58, 41, 642354)),
        ),
    ]
